[package]
name = "day14b"
version = "0.1.0"
authors = ["Jeff Lee <jeffomatic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.3.1"
